### ISSUE TITLE
Suggestions of vocabularies services, open vocabularies and software

### ISSUE THREAD

**Issue by Isbema** [E-RIHS/hs-interoperability#3]
Hi,
 
A few suggestions to add:

-Server Services:

**Research Vocabularies Australia** https://vocabs.ardc.edu.au/: Research Vocabularies Australia helps you find, access, and reuse vocabularies for research. Some vocabularies are hosted by the Australian Research Data Commons (ARDC) and can be accessed directly through Research Vocabularies Australia. Otherwise Research Vocabularies Australia provides a link to the vocabulary owner’s web page.
Research Vocabularies Australia also allows you to [create and/or publish a vocabulary ](https://vocabs.ardc.edu.au/vocabs/page/contribute)as well as [integrate an existing vocabulary into your own system](https://vocabs.ardc.edu.au/vocabs/page/use).

-Server software

BARTOC is promoting a community based effort to identify and collect basic information about software for controlled vocabularies which can be useful to us: https://github.com/gbv/bartoc.org/wiki/Software-for-controlled-vocabularies

-Open Vocabularies

**TADIRAH** http://www.tadirah.info/: Taxonomy of Digital Research Activities in the Humanities was designed to help community-driven sites and projects structure their digital humanities (DH) content and gain better visibility.TaDiRAH provides terminology for DH research activities as well as scope notes that also explain the methods associated with them.

A clarification on COAR Vocabularies: There are 3 for research outputs types (https://vocabularies.coar-repositories.org/resource_types/), access rights (https://vocabularies.coar-repositories.org/access_rights/) and versions of resource types (https://vocabularies.coar-repositories.org/version_types/)

**PARTHENOS Vocabularies** https://isl.ics.forth.gr/bbt-federated-thesaurus/PARTHENOS/en/ PARTHENOS vocabularies is the research outcome of the H2020 Project “PARTHENOS Pooling Activities, Resources and Tools for Heritage E-research Networking, Optimization and Synergies” (INFRADEV-4-2014/2015, GA #654119, http://www.parthenos-project.eu). It is provided under CC-BY 4.0 distribution license. This is a modified version that contains skos:broadMatch links from PARTHENOS concepts to BackBoneThesaurus (BBT) concepts.

**GEMET** GEMET, the GEneral Multilingual Environmental Thesaurus, has been developed as an indexing, retrieval and control tool for the European Topic Centre on Catalogue of Data Sources (ETC/CDS) and the European Environment Agency (EEA), Copenhagen. (https://www.eionet.europa.eu/gemet/).

**ICONGLASS** https://iconclass.org/
Iconclass is a classification system designed for art and iconography. It is the most widely accepted scientific tool for the description and retrieval of subjects represented in images (works of art, book illustrations, reproductions, photographs, etc.) and is used by museums and art institutions around the world.

**Tesauros del Patromonio Cultural de España**: http://tesauros.mecd.es/tesauros/tesauros: A bunch of thesauri to describe aspects of Spanish cultural heritage in linked data format,  

List of other Cultural Heritage Thesauri maintained by Spain's Ministry of Culture: https://www.culturaydeporte.gob.es/cultura/areas/museos/mc/ceres/enlaces/vocabularios-y-tesauros-sobre-patrimonio-cultural.html

Hope this helps!
Isabel

**Comment by jpadfield** [comment]
Thanks, I have added these to the page (https://github.com/E-RIHS/hs-interoperability/blob/main/Vocabulary/README.md) sorry for the slow response.
